Feature/service
exo-addons/office-online pull request #1
Opened 2019-10-16 12:21 UTC by VladMartyshevskyi

Work on OfficeOnlineEditorService and WOPI Discovery.

2019-10-16 14:04 UTC, pnedonosko commented on services/src/main/java/org/exoplatform/officeonline/Constants.java
> +  public static final String ACCESS_TOKEN_ATTRIBUTE              = "accessToken";
I propose move WOPI only and internally used constants to wopi plugin package. Others general to the add-on could live on logic entities or service level.

2019-10-16 14:14 UTC, pnedonosko commented on services/src/main/java/org/exoplatform/officeonline/OfficeOnlineEditorService.java
> +      String remoteUser = WCMCoreUtils.getRemoteUser();
Ensure this will return an username in all cases: WebUI request, REST/Servlet request.

2019-10-16 14:18 UTC, pnedonosko commented on services/src/main/java/org/exoplatform/officeonline/OfficeOnlineEditorService.java
> +  public Map<String, Serializable> checkFileInfo(String userSchema,
This looks as pure WOPI stuff as well as other methods in this commit. Let's move such API calls out of the service to WOPI-related object (its name good to set to 'server', 'provider' or 'SPI').

2019-10-16 14:32 UTC, VladMartyshevskyi commented on services/src/main/java/org/exoplatform/officeonline/OfficeOnlineEditorService.java
> +      String remoteUser = WCMCoreUtils.getRemoteUser();
It's going to be fixed in the next commits by setting user ConversationState. 
Updated: https://github.com/exo-addons/office-online/pull/1/commits/d2f90a1fb9e5ab33d344a3b0b925d18d61c33e74

2019-10-17 12:29 UTC, pnedonosko requested changes
As was agreed in Slack discussion, we move WOPI related stuff to SPI layer which should be configured via service component-plugin and act as a singleton. 
Next, we have two kinds of REST services:
- WOPI endpoints for use by Office
- OfficeEditor services for eXo portal pages (including editor page)

2019-10-17 15:25 UTC, pnedonosko commented on services/src/main/java/org/exoplatform/officeonline/rest/WOPIService.java
> +@Path("/officeonline/wopi")
Let's use simpler /wopi

2019-10-17 15:28 UTC, pnedonosko requested changes

2019-10-17 15:28 UTC, pnedonosko commented on services/src/main/java/org/exoplatform/officeonline/rest/WOPIService.java
> +    this.wopiSPI = editorService.getWOPIService();
This class name is WOPIService, a method editorService.getWOPIService() sounds a but misleading, let's change it to getWOPIConnector() and related internal class name change to WOPIConnector also.

2019-10-17 15:31 UTC, pnedonosko approved these changes

2019-10-17 15:41 UTC, VladMartyshevskyi commented
All requested changes will be in the next PR.

2019-10-17 15:41 UTC, merged