Feature/editor buttons
exo-addons/office-online pull request #29
Opened 2020-04-07 11:28 UTC by VladMartyshevskyi

Editor buttons integration with ECMS.

2020-04-08 09:58 UTC, pnedonosko requested changes

2020-04-08 09:58 UTC, pnedonosko commented on services/src/main/java/org/exoplatform/officeonline/documents/OfficeOnlineDocumentEditorPlugin.java
> +    link = link != null ? new StringBuilder().append("'").append(link).append("'").toString() : "null".intern();
Don't use `intern()` and is it correct to return `null` when no link present?

2020-04-08 09:58 UTC, pnedonosko commented on services/src/main/java/org/exoplatform/officeonline/documents/OfficeOnlineDocumentEditorPlugin.java
> +    link = link != null ? new StringBuilder().append("'").append(link).append("'").toString() : "null".intern();
In case of `null`, ensure client logic handle this correct and user friendly.

2020-04-22 13:06 UTC, VladMartyshevskyi commented on services/src/main/java/org/exoplatform/officeonline/documents/OfficeOnlineDocumentEditorPlugin.java
> +    link = link != null ? new StringBuilder().append("'").append(link).append("'").toString() : "null".intern();
fixed: https://github.com/exo-addons/office-online/pull/29/commits/7f2bcebbf2cd35dd84f8069993c0266550ee7e2d

2020-04-24 09:32 UTC, pnedonosko approved these changes

2020-04-24 11:07 UTC, merged